In [1]:
%pip install eurostat

Collecting eurostat
  Downloading eurostat-1.1.1-py3-none-any.whl.metadata (26 kB)
Requirement already satisfied: pandas in /home/codespace/.local/lib/python3.12/site-packages (from eurostat) (2.2.3)
Requirement already satisfied: requests in /home/codespace/.local/lib/python3.12/site-packages (from eurostat) (2.32.3)
Requirement already satisfied: numpy>=1.26.0 in /home/codespace/.local/lib/python3.12/site-packages (from pandas->eurostat) (2.2.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas->eurostat) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/codespace/.local/lib/python3.12/site-packages (from pandas->eurostat) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /home/codespace/.local/lib/python3.12/site-packages (from pandas->eurostat) (2025.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/codespace/.local/lib/python3.12/site-packages (from requests->eurostat) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /home/codespace/.local/lib/python3.12/site-packages (from requests->eurostat) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/codespace/.local/lib/python3.12/site-packages (from requests->eurostat) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/codespace/.local/lib/python3.12/site-packages (from requests->eurostat) (2025.1.31)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->eurostat) (1.17.0)
Downloading eurostat-1.1.1-py3-none-any.whl (16 kB)
Installing collected packages: eurostat
Successfully installed eurostat-1.1.1

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import eurostat

In [3]:
data=eurostat.get_data_df('avia_par_fi')

In [4]:
data

,freq,unit,tra_meas,airp_pr\TIME_PERIOD,1997,1997-Q1,1997-Q2,1997-Q3,1997-Q4,1998,...,2024-07,2024-08,2024-09,2024-10,2024-11,2024-12,2024-Q1,2024-Q2,2024-Q3,2024-Q4
0,A,FLIGHT,CAF_PAS,FI_EFHK_AE_OMDB,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A,FLIGHT,CAF_PAS,FI_EFHK_AT_LOWW,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A,FLIGHT,CAF_PAS,FI_EFHK_BE_EBBR,2.0,NaN,NaN,NaN,NaN,2437.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A,FLIGHT,CAF_PAS,FI_EFHK_CH_LSGG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A,FLIGHT,CAF_PAS,FI_EFHK_CH_LSZH,6.0,NaN,NaN,NaN,NaN,1947.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7249,Q,SEAT,ST_PAS_DEP,FI_EFVA_FI_EFKK,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7250,Q,SEAT,ST_PAS_DEP,FI_EFVA_FI_EFTU,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7251,Q,SEAT,ST_PAS_DEP,FI_EFVA_LV_EVRA,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7252,Q,SEAT,ST_PAS_DEP,FI_EFVA_SE_ESSA,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6928.0,12306.0,10540.0,8793.0
7253,Q,SEAT,ST_PAS_DEP,FI_EFVA_TR_LTAI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
data.freq.unique()

array(['A', 'M', 'Q'], dtype=object)

annually, monthly, quarterly

In [6]:
data.unit.unique()

array(['FLIGHT', 'PAS', 'SEAT'], dtype=object)

flights, passengers, seats

In [7]:
data.tra_meas.unique()

array(['CAF_PAS', 'CAF_PAS_ARR', 'CAF_PAS_DEP', 'PAS_BRD', 'PAS_BRD_ARR',
       'PAS_BRD_DEP', 'PAS_CRD', 'PAS_CRD_ARR', 'PAS_CRD_DEP', 'ST_PAS',
       'ST_PAS_ARR', 'ST_PAS_DEP'], dtype=object)

arrival and departure. But what is CAF, PAS_BRD, PAS_CRD, ST_PAS? See [metadata](https://ec.europa.eu/eurostat/cache/metadata/en/avia_pa_esms.htm)
> In the tables of the sub-domain "Transport measurement - Passengers", data are broken down by passengers on board (arrivals, departures and total), passengers carried (arrivals, departures and total) and passenger commercial air flights (arrival, departures and total). Additionally, the tables of collection "Detailed air transport by reporting country and routes" provide data on seats available (arrival, departures and total). The data is presented at monthly, quarterly and annual level.

In [11]:
data.query("freq=='A'").dropna(axis='columns',how='all').groupby(['unit','tra_meas']).sum(numeric_only=True)

                         1997        1998        1999        2000        2001  \
unit   tra_meas
FLIGHT CAF_PAS           45.0    197770.0    184201.0    185495.0    191963.0
       CAF_PAS_ARR        8.0     97080.0     88751.0     89043.0     93277.0
       CAF_PAS_DEP       37.0    100690.0     95450.0     96452.0     98686.0
PAS    PAS_BRD      1810570.0  10936248.0  10946428.0  11307792.0  11923029.0
       PAS_BRD_ARR   463121.0   5327834.0   5289627.0   5440416.0   5762537.0
       PAS_BRD_DEP  1347449.0   5608414.0   5656801.0   5867376.0   6160492.0
       PAS_CRD      5299187.0  10689285.0  10232893.0  11541420.0         0.0
       PAS_CRD_ARR  2664447.0   5341189.0   5098264.0   5733867.0         0.0
       PAS_CRD_DEP  2634740.0   5348096.0   5134629.0   5807553.0         0.0
SEAT   ST_PAS       3429932.0  17043025.0  18993371.0  21174097.0  20971790.0
       ST_PAS_ARR    849646.0   8302640.0   9229886.0  10230782.0  10201750.0
       ST_PAS_DEP   2580286.0   8740385.0   9763485.0  10943315.0  10770040.0

                          2002        2003        2004        2005  \
unit   tra_meas
FLIGHT CAF_PAS        170382.0    181697.0    194028.0    195076.0
       CAF_PAS_ARR     85046.0     90988.0     96945.0     97581.0
       CAF_PAS_DEP     85336.0     90709.0     97083.0     97495.0
PAS    PAS_BRD      11600292.0  10952423.0  12339929.0  12741972.0
       PAS_BRD_ARR   5782206.0   5470102.0   6153274.0   6366228.0
       PAS_BRD_DEP   5818086.0   5482321.0   6186655.0   6375744.0
       PAS_CRD      10839090.0  10930241.0  12308426.0  12750677.0
       PAS_CRD_ARR   5404755.0   5451466.0   6143251.0   6372298.0
       PAS_CRD_DEP   5434335.0   5478775.0   6165175.0   6378379.0
SEAT   ST_PAS       19311666.0  20585240.0  21723196.0  21352486.0
       ST_PAS_ARR    9629947.0  10288799.0  10845461.0  10677333.0
       ST_PAS_DEP    9681719.0  10296441.0  10877735.0  10675153.0

                          2006  ...        2015        2016        2017  \
unit   tra_meas                 ...
FLIGHT CAF_PAS        197899.0  ...    168835.0    167418.0    179703.0
       CAF_PAS_ARR     98734.0  ...     84416.0     83700.0     89821.0
       CAF_PAS_DEP     99165.0  ...     84419.0     83718.0     89882.0
PAS    PAS_BRD      13540801.0  ...  17035094.0  17807566.0  19759529.0
       PAS_BRD_ARR   6754097.0  ...   8515102.0   8890825.0   9859666.0
       PAS_BRD_DEP   6786704.0  ...   8519992.0   8916741.0   9899863.0
       PAS_CRD      13611788.0  ...  17102056.0  17781770.0  19624069.0
       PAS_CRD_ARR   6801389.0  ...   8546975.0   8875063.0   9792169.0
       PAS_CRD_DEP   6810399.0  ...   8555081.0   8906707.0   9831900.0
SEAT   ST_PAS       21065064.0  ...  23069804.0  23659378.0  25778514.0
       ST_PAS_ARR   10503534.0  ...  11536596.0  11832171.0  12879491.0
       ST_PAS_DEP   10561530.0  ...  11533208.0  11827207.0  12899023.0

                          2018        2019       2020       2021        2022  \
unit   tra_meas
FLIGHT CAF_PAS        196878.0    199900.0    52532.0    56169.0    109799.0
       CAF_PAS_ARR     98315.0     99691.0    26338.0    28061.0     54861.0
       CAF_PAS_DEP     98563.0    100209.0    26194.0    28108.0     54938.0
PAS    PAS_BRD      22093446.0  22907765.0  4532164.0  4498861.0  12195311.0
       PAS_BRD_ARR  11009409.0  11407817.0  2284388.0  2243228.0   6077816.0
       PAS_BRD_DEP  11084037.0  11499948.0  2247776.0  2255633.0   6117495.0
       PAS_CRD      21971125.0  22846977.0  4509433.0  4472129.0  12135043.0
       PAS_CRD_ARR  10961717.0  11379965.0  2277469.0  2232577.0   6056861.0
       PAS_CRD_DEP  11009408.0  11467012.0  2231964.0  2239552.0   6078182.0
SEAT   ST_PAS       29146224.0  29960839.0  7927288.0  7636274.0  16591077.0
       ST_PAS_ARR   14555956.0  14938197.0  3958331.0  3799732.0   8287926.0
       ST_PAS_DEP   14590268.0  15022642.0  3968957.0  3836542.0   8303151.0

                          2023        2024
unit   tra_meas
FLIGHT CAF_PAS        129610.0    144295.0
       CAF_PAS_ARR     64816.0     72143.0
       CAF_PAS_DEP     64794.0     72152.0
PAS    PAS_BRD      15225813.0  16801188.0
       PAS_BRD_ARR   7615499.0   8393443.0
       PAS_BRD_DEP   7610314.0   8407745.0
       PAS_CRD      15153284.0  16730271.0
       PAS_CRD_ARR   7590489.0   8367603.0
       PAS_CRD_DEP   7562795.0   8362668.0
SEAT   ST_PAS       19648767.0  22122525.0
       ST_PAS_ARR    9825702.0  11057941.0
       ST_PAS_DEP    9823065.0  11064584.0

[12 rows x 28 columns]

In [8]:
data.query("freq=='A' and unit=='FLIGHT'").dropna(axis='columns',how='all')

,freq,unit,tra_meas,airp_pr\TIME_PERIOD,1997,1998,1999,2000,2001,2002,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,A,FLIGHT,CAF_PAS,FI_EFHK_AE_OMDB,NaN,NaN,NaN,NaN,269.0,NaN,...,NaN,564.0,575.0,754.0,913.0,NaN,177.0,NaN,NaN,NaN
1,A,FLIGHT,CAF_PAS,FI_EFHK_AT_LOWW,NaN,NaN,NaN,NaN,1979.0,1875.0,...,1494.0,1470.0,1456.0,1456.0,1442.0,573.0,631.0,1378.0,1720.0,1785.0
2,A,FLIGHT,CAF_PAS,FI_EFHK_BE_EBBR,2.0,2437.0,2457.0,3062.0,3016.0,2879.0,...,2322.0,2151.0,2293.0,2254.0,2278.0,885.0,752.0,1787.0,1821.0,1834.0
3,A,FLIGHT,CAF_PAS,FI_EFHK_CH_LSGG,NaN,NaN,NaN,NaN,NaN,NaN,...,1440.0,NaN,NaN,999.0,1149.0,NaN,NaN,NaN,NaN,986.0
4,A,FLIGHT,CAF_PAS,FI_EFHK_CH_LSZH,6.0,1947.0,2104.0,2150.0,2065.0,1405.0,...,2525.0,1821.0,1474.0,1468.0,1475.0,821.0,981.0,1453.0,1434.0,1447.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
625,A,FLIGHT,CAF_PAS_DEP,FI_EFVA_FI_EFKK,NaN,518.0,511.0,381.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
626,A,FLIGHT,CAF_PAS_DEP,FI_EFVA_FI_EFTU,NaN,NaN,367.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
627,A,FLIGHT,CAF_PAS_DEP,FI_EFVA_LV_EVRA,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
628,A,FLIGHT,CAF_PAS_DEP,FI_EFVA_SE_ESSA,NaN,1790.0,1779.0,1840.0,1835.0,1350.0,...,934.0,945.0,980.0,989.0,1007.0,NaN,NaN,NaN,198.0,448.0
629,A,FLIGHT,CAF_PAS_DEP,FI_EFVA_TR_LTAI,NaN,NaN,NaN,NaN,NaN,NaN,...,58.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Events affecting data:  
 - 2020 Covid.
 - 2021 EU sanctions on Belarus.
 - 2022 Ukraine war and sanctions on Russia.

In [ ]:
#https://raw.githubusercontent.com/jpatokal/openflights/master/data/routes.dat

#https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat